- name: Make the Swap inactive
  become: true
  command: swapoff -a

- name: create kubernetes repo variable
  become: true
  shell: echo "deb [allow-insecure=yes] http://10.140.79.120:8081/apt-repo ./" > /etc/apt/sources.list

- name: update the packages
  become: true
  shell: apt update -y

- name: Install required packages
  become: true
  apt:
    name: {{ item }}
    state: present
    allow-unauthenticated: yes
  with_items:
    - docker.io
    - apt-transport-https
    - kubeadm=1.22.0-00
    - kubelet=1.22.0-00
    - kubectl=1.22.0-00
    - ebtables
    - acl

- name: Creating a daemon json
  become: true
  copy:
   dest: "/etc/docker/daemon.json"
   content: |
    {
    "exec-opts": ["native.cgroupdriver=systemd"],
    "insecure-registries": ["10.140.79.120:5000"]
    }

- name: restarting the docker
  become: true
  shell: |
    systemctl daemon-reload
    systemctl restart docker
    systemctl restart kubelet

- name: Login to docker registry
  shell: docker login 10.140.79.120:5000 -u iflocalregistry -p '&mF&FWnu'

- name: Get k8s docker images
  shell: kubeadm config images pull --image-repository 10.140.79.120:5000

- name: Get flannel docker images
  shell: "docker pull 10.140.79.120:5000/{{ item }}"
  with_items:
     - mirrored-flannelcni-flannel:v0.19.0
     - mirrored-flannelcni-flannel-cni-plugin:v1.1.0

- name: Get kubernetes-dashboard docker images
  shell: "docker pull 10.140.79.120:5000/{{ item }}"
  with_items:
     - dashboard:v2.0.0
     - metrics-scraper:v1.0.4
  
- name: Get nginx-ingress-controller docker images
  shell: "docker pull 10.140.79.120:5000/{{ item }}"
  with_items:
     - controller:v1.2.0
     - kube-webhook-certgen:v1.1.1

