- name: Create apt repo variable
  become: true
  shell: echo "deb [allow-insecure=yes] http://10.140.79.120:8081/apt-repo ./" > /etc/apt/sources.list

- name: Update apt packages
  become: true
  shell: apt update -y

- name: Install docker
  apt:
    name: docker.io
    state: present
    allow-unauthenticated: yes

- name: Install apt transport https
  apt:
    name: apt-transport-https
    state: present
    allow-unauthenticated: yes
