- name: Create yaml folder
  file: name={{ yaml_dir }} state=directory

- name: Create yaml filses
  template: src={{ item }} dest={{ yaml_dir }}/{{ item }}
  with_items:
  - kubernetes-dashboard.yaml
  - nginx-ingress-controller.yaml
                    
- name: Install kubernetes-dashboard 
  raw:  kubectl get po -n kube-system|grep dashboard || kubectl create -f /root/.kube/kube-apps/kubernetes-dashboard.yaml
                                
- name: Install ingress-controller
  raw: kubectl get po -n kube-system|grep ingress || kubectl create -f /root/.kube/kube-apps/nginx-ingress-controller.yaml
